[theme]
base = "dark"
primaryColor = "#3FA66B"
backgroundColor = "#0D0F0C"
secondaryBackgroundColor = "#16190F"
textColor = "#E8E6DC"
font = "monospace"

[server]
runOnSave = true
enableStaticServing = true
